/* One lazy browser worker; only the number-guide crop is sent to OCR, never card artwork. */
window.DCBOCR=(()=>{
 let worker=null,loading=null,script=null,revision=0,locked=false,lastStarted=0,cancel=null;
 const assetRoot=new URL('vendor/ocr/',document.currentScript.src);
 function load(){if(window.Tesseract)return Promise.resolve();if(!script){script=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL('tesseract.min.js',assetRoot);s.onload=resolve;s.onerror=()=>{s.remove();script=null;reject(Error('番号読み取りの準備に失敗しました。'));};document.head.append(s);});}return script;}
 async function engine(){if(worker)return worker;if(!loading){const token=revision;const promise=(async()=>{await load();const next=await Tesseract.createWorker('eng',1,{workerPath:new URL('worker.min.js',assetRoot).href,corePath:new URL('core/',assetRoot).href,langPath:new URL('lang/',assetRoot).href,workerBlobURL:false,cacheMethod:'none',errorHandler:e=>{if(debug())console.warn('[DCBOCR]',e);}});if(token!==revision){await next.terminate();throw Error('読み取りを中断しました。');}worker=next;await next.setParameters({tessedit_pageseg_mode:Tesseract.PSM.SINGLE_LINE,tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-',user_defined_dpi:'300'});return next;})();loading=promise;promise.then(()=>{if(loading===promise)loading=null;},()=>{if(loading===promise)loading=null;});}return loading;}
 const debug=()=>['localhost','127.0.0.1'].includes(location.hostname)||new URLSearchParams(location.search).get('debug')==='ocr';
 const sleep=ms=>new Promise(r=>setTimeout(r,ms));
 async function readNumber({image}){if(!image)throw Error('番号の画像がありません。');if(locked)throw Error('読み取り中です。');locked=true;const token=revision;const cancelled=new Promise((_,reject)=>{cancel=()=>reject(Error('読み取りを中断しました。'));});const operation=(async()=>{await sleep(Math.max(0,750-(Date.now()-lastStarted)));if(token!==revision)throw Error('読み取りを中断しました。');lastStarted=Date.now();const w=await engine();if(token!==revision)throw Error('読み取りを中断しました。');const {data}=await w.recognize(image,{}, {text:true});if(token!==revision)throw Error('読み取りを中断しました。');return{text:data.text||'',confidence:Number(data.confidence)||0};})();try{return await Promise.race([operation,cancelled]);}catch(e){if(token===revision){const old=worker;worker=null;loading=null;old?.terminate().catch(()=>{});}throw e;}finally{if(token===revision){locked=false;cancel=null;}}}
 function stop(){revision++;cancel?.();cancel=null;locked=false;loading=null;const old=worker;worker=null;old?.terminate().catch(()=>{});}
 function crop(video,view,guide){if(!video.videoWidth||!video.videoHeight||video.readyState<2)throw Error('カメラの映像を待って、もう一度お試しください。');const scale=Math.max(view.width/video.videoWidth,view.height/video.videoHeight),ox=(video.videoWidth*scale-view.width)/2,oy=(video.videoHeight*scale-view.height)/2;const x=Math.max(0,(guide.left-view.left+ox)/scale),y=Math.max(0,(guide.top-view.top+oy)/scale),w=Math.min(video.videoWidth-x,guide.width/scale),h=Math.min(video.videoHeight-y,guide.height/scale);if(w<=0||h<=0)throw Error('番号の枠を確認してください。');const canvas=document.createElement('canvas'),factor=Math.min(3,1200/w);canvas.width=Math.max(1,Math.round(w*factor));canvas.height=Math.max(1,Math.round(h*factor));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(video,x,y,w,h,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4){const gray=.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2],value=Math.max(0,Math.min(255,(gray-128)*1.15+128));pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=value;}ctx.putImageData(pixels,0,0);return canvas;}
 function debugResult(result,match){if(debug())console.debug('[DCBOCR]',{raw:result.text,normalized:match.read,confidence:result.confidence,match:match.kind,level:match.level,candidateCount:match.candidates.length});}
 return {readNumber,crop,stop,debugResult};
})();
window.DCBOCRPolicy=(()=>{
 const registered=new Map(),hold=10000;
 const canAuto=(result,match)=>result.confidence>=85&&match.kind==='exact'&&match.level==='literal'&&match.candidates.length===1;
 const available=(id,now=Date.now())=>!registered.has(id)||now-registered.get(id)>=hold;
 return {canAuto,available,mark:(id,now=Date.now())=>registered.set(id,now),hold};
})();
