window.DCBRegistration=(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let root,stream,stage='scan',selected=null,candidates=[],message='',input='',reading=false,busy=false,sessionCount=0,timer,revision=0,cameraMessage='',cameraPending=false,ocrTimer=null,ocrResolve=null,ocrSource=false,scanZoom=1.5;
 let autoPending=false,captureRevision=0,pendingPhoto=null,previewURL=null,retakeId=null,resume=null,preserveNext=false,historyView=false,drawVersion=0,thumbURLs=[];let recent=[];try{const v=JSON.parse(localStorage.getItem('dcb-registration-history')||'[]');if(Array.isArray(v))recent=v.filter(r=>r&&typeof r.cardId==='string'&&Number.isFinite(r.at)).slice(0,100);}catch{}
 let mode='confirm';try{mode=localStorage.getItem('dcb-registration-mode')==='fast'?'fast':'confirm';}catch{}
 const cameraControl=DCBCamera.create(state=>{if(root&&stage==='scan'&&!reading){const field=root.querySelector('#scan-number');if(field)input=field.value;}stream=state.stream;cameraPending=state.pending;if(stage==='scan'&&stream&&!state.pending&&!state.zoom.busy)scanZoom=state.zoom.value;cameraMessage=state.error?.message||state.zoom?.message||'';draw();},{highResolution:true,defaultZoom:1.5});
 const getMode=()=>mode;
 function setMode(value){mode=value==='fast'?'fast':'confirm';try{localStorage.setItem('dcb-registration-mode',mode);}catch{}return mode;}
 function stopReading(){revision++;clearTimeout(ocrTimer);ocrTimer=null;ocrResolve?.();ocrResolve=null;reading=false;DCBOCR.stop();}
 function clearPreview(){if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;pendingPhoto=null;}
 function cancelCapture(){captureRevision++;autoPending=false;}
 function stop(){if(root&&preserveNext&&!retakeId&&!historyView){resume={stage:stage==='success'?'scan':stage,selected,candidates,message,ocrSource,input:root.querySelector('#scan-number')?.value??input,sessionCount,pendingPhoto,scroll:window.scrollY};}preserveNext=false;stopReading();cancelCapture();clearTimeout(timer);cameraControl.stop();stream=null;root=null;cameraPending=false;busy=false;reading=false;clearPreview();thumbURLs.forEach(URL.revokeObjectURL);thumbURLs=[];}
 function mount(element,options={}){stop();root=element;retakeId=options.retakeId||null;historyView=!!options.history;stage='scan';selected=null;candidates=[];message='';input='';sessionCount=0;cameraMessage='';ocrSource=false;if(retakeId){selected=DCBData.cards.find(c=>c.id===retakeId);if(!selected){location.hash='#binder';return;}stage='capture';}else if(!historyView&&resume){const state=resume;resume=null;stage=state.stage;selected=state.selected;candidates=state.candidates||[];message=state.message||'';ocrSource=!!state.ocrSource;input=state.input;sessionCount=state.sessionCount;pendingPhoto=state.pendingPhoto;if(pendingPhoto)previewURL=URL.createObjectURL(pendingPhoto);requestAnimationFrame(()=>window.scrollTo(0,state.scroll));}draw();}
 function recordRecent(card){recent=[{cardId:card.id,at:Date.now()},...recent].slice(0,100);try{localStorage.setItem('dcb-registration-history',JSON.stringify(recent));}catch{cameraMessage='登録履歴をこの端末に保存できませんでした。';}}
 function recentHTML(all=false){const items=recent.filter(r=>DCBData.cards.some(c=>c.id===r.cardId)).slice(0,all?100:3);return `<section class="scan-recent"><div class="scan-recent-heading"><h2>${all?'登録履歴':'直近の登録'}</h2>${!all&&items.length?'<button class="btn-text btn-compact" data-scan="history">履歴を見る</button>':''}</div><div class="scan-recent-list">${items.map(r=>{const c=DCBData.cards.find(c=>c.id===r.cardId);return `<button type="button" class="scan-recent-item" data-recent-card="${c.id}"><span class="scan-recent-thumb" data-recent-photo="${c.id}" style="background:${c.color}">✧</span><span>${esc(c.name)}</span>${all?`<small>${new Date(r.at).toLocaleDateString('ja-JP')}</small>`:''}</button>`;}).join('')||'<p class="scan-note">登録はまだありません。</p>'}</div></section>`;}
 function loadRecentPhotos(){const token=drawVersion;thumbURLs.forEach(URL.revokeObjectURL);thumbURLs=[];root?.querySelectorAll('[data-recent-photo]').forEach(el=>DCBPhotos.read(el.dataset.recentPhoto).then(r=>{if(!r?.blob||!root||token!==drawVersion||!el.isConnected)return;const url=URL.createObjectURL(r.blob);thumbURLs.push(url);const img=document.createElement('img');img.src=url;img.alt='';el.replaceChildren(img);}).catch(()=>{}));}
 const choice=c=>`<button type="button" class="scan-choice" data-pick="${c.id}"><span class="scan-mini" style="--scan-color:${c.color}">✧</span><span><strong>${esc(c.name)}</strong><span>${esc(c.cardNumber)} ${esc(c.rarity||'')}</span><small>${esc(c.specification||c.scanVariant||'')}</small></span><span>→</span></button>`;
 function draw(){if(!root)return;drawVersion++;if(historyView){root.innerHTML=`<div class="registration-view">${DCBUI.header({title:'登録履歴',action:'<button class="btn-text btn-compact" data-scan="history-back">戻る</button>'})}<main class="scan-main">${recentHTML(true)}</main></div>`;loadRecentPhotos();return;}
  const existingVideo=root.querySelector('.registration-view .scan-camera video');
  const capturing=stage==='capture',preview=stage==='preview',success=stage==='success';
  const html=`<div class="registration-view">${DCBUI.header({title:retakeId?'写真を撮り直す':'カード登録',action:`<button class="page-header-action btn-text btn-compact" type="button" data-scan="exit" ${busy?'disabled':''}>${retakeId?'キャンセル':'登録終了'}</button>`})}<main class="scan-main">${retakeId?'':`<div class="scan-modes" role="group" aria-label="登録モード"><button type="button" data-mode="confirm" aria-pressed="${mode==='confirm'}" ${busy||reading||autoPending||retakeId?'disabled':''}>確認登録</button><button type="button" data-mode="fast" aria-pressed="${mode==='fast'}" ${busy||reading||autoPending||retakeId?'disabled':''}>高速登録</button></div>`}<p class="scan-instruction" role="status">${success?'✓ 登録しました':preview?'撮影した画像を確認してください':capturing?'カード全体を枠に合わせてください':'カードから少し離して、番号を枠の中央に合わせてください'}</p><div class="scan-camera ${capturing||preview?'scan-camera-full':''} ${preview?'scan-preview':''}"><video autoplay muted playsinline aria-label="カード登録用カメラ"></video><div class="scan-camera-empty" ${stream?'hidden':''}>${DCBUI.icon('camera','scan-camera-icon')}<span>${cameraPending?'カメラを起動中…':'カメラプレビュー'}</span>${!cameraPending?`<button class="btn-secondary" type="button" data-scan="camera">${cameraControl.state().error&&cameraControl.state().error.name!=='Stopped'?'もう一度試す':'カメラを起動'}</button>`:''}</div><div class="scan-guide" aria-hidden="true"></div>${preview?`<img class="scan-preview-image" src="${previewURL}" alt="撮影したカードの確認画像">`:autoPending?'<span class="scan-capture-status" role="status">'+esc(cameraMessage||'カードを枠に合わせてください…')+'</span>':''}${success?`<div class="scan-success"><strong>✓ 登録しました</strong><span>${selected.cardNumber}</span><span>${esc(selected.name)}</span></div>`:''}</div>${cameraMessage?`<p class="scan-message" role="status">${esc(cameraMessage)}</p>`:''}
  ${stage==='scan'&&stream?zoomControls():''}
  ${stage==='scan'?`<div class="scan-ocr-actions"><button class="btn-primary" type="button" data-scan="ocr" ${reading||!stream||cameraPending?'disabled':''}>${reading?'読み取り中…':'読み取り開始'}</button><button class="btn-text" type="button" data-scan="manual">手入力する</button>${reading?'<button class="btn-text" type="button" data-scan="stop-reading">中止</button>':''}</div>`:''}
  ${preview?`<div class="scan-preview-actions"><button class="btn-primary" data-scan="confirm-photo" ${busy?'disabled':''}>${busy?'保存中…':'これで登録'}</button><button class="btn-secondary" data-scan="retake-photo" ${busy?'disabled':''}>撮り直し</button></div>`:success?`<button type="button" class="scan-primary btn-primary" data-scan="next">次のカードへ</button>`:capturing?`<div class="scan-match"><span>このカードです</span>${choice(selected)}</div><div class="scan-capture-actions"><button class="btn-primary" data-scan="auto" ${busy||autoPending||cameraPending?'disabled':''}>自動撮影</button><button class="btn-secondary" data-scan="capture" ${busy||autoPending||cameraPending?'disabled':''}>撮影する</button>${autoPending?'<button class="btn-text" data-scan="cancel-capture">自動撮影を中止</button>':''}${!retakeId?`<button class="btn-text" data-scan="without-photo" ${busy?'disabled':''}>写真なしで登録</button><button class="btn-text" data-scan="retry" ${busy?'disabled':''}>番号を読み直す</button>`:''}</div><p class="scan-note">${stream?'枠の中でカードを動かさずにお待ちください。':'カメラを起動してカード全体を合わせてください。'}</p>`:`<form id="scan-number-form"><label for="scan-number">手入力 </label><div class="scan-number-row"><input class="ui-input" id="scan-number" name="number" maxlength="40" autocomplete="off" spellcheck="false" placeholder="E1-01" value="${esc(input)}" ${reading?'disabled':''}><button type="submit" class="scan-primary btn-primary" ${reading?'disabled':''}>${reading?'読み取り中…':'番号を読み取る'}</button></div></form>${message?`<p class="scan-message" role="alert">${esc(message)}</p>`:''}${candidates.length?`<div class="scan-candidates">${candidates.map(choice).join('')}</div>`:''}${message?`<button class="btn-secondary" type="button" data-scan="ocr" ${!stream?'disabled':''}>再読み取り</button>`:''}<p class="scan-note">${mode==='fast'?'一致したら所持枚数＋1。全体撮影を省略します。':'番号を照合してから全体を撮影します。'}</p>`}
  ${!retakeId?`<div class="scan-session"><span>今回の登録</span><strong>${sessionCount}枚</strong></div>${recentHTML()}`:''}</main></div>`;
  // Keep the live video and its camera container continuously attached to the document.
  if(existingVideo){const template=document.createElement('div');template.innerHTML=html;const currentMain=root.querySelector('.scan-main'),nextMain=template.querySelector('.scan-main'),camera=currentMain.querySelector('.scan-camera');root.querySelector('.page-header').replaceWith(template.querySelector('.page-header'));for(const n of [...currentMain.childNodes])if(n!==camera)n.remove();let before=true;for(const n of [...nextMain.childNodes]){if(n.nodeType===1&&n.classList.contains('scan-camera')){camera.className=n.className;for(const child of [...camera.childNodes])if(child!==existingVideo)child.remove();for(const child of [...n.childNodes])if(child.nodeName!=='VIDEO')camera.append(child);before=false;}else if(before)currentMain.insertBefore(n,camera);else currentMain.append(n);}}
  else root.innerHTML=html;
  cameraControl.attach(root.querySelector('video'));loadRecentPhotos();
 }
 async function camera(){if(!root||cameraPending)return;await cameraControl.start(root.querySelector('video'));if(root&&stream&&stage==='capture'){await cameraControl.setZoom(Math.max(cameraControl.zoomInfo().min,Math.min(cameraControl.zoomInfo().max,1)));if(root&&stage==='capture')capture(true);}}
 async function read(){if(!root||reading||busy||stage!=='scan')return;ocrSource=false;input=root.querySelector('#scan-number').value;reading=true;message='';candidates=[];draw();const token=revision;
  let text;try{text=await Promise.resolve(input);}catch{if(token!==revision||!root)return;reading=false;message='カード番号を読み取れませんでした。もう一度番号を枠内に合わせてください。';draw();return;}if(token!==revision||!root)return;reading=false;
  const result=DCBMatcher.match(text,DCBData.cards);candidates=result.candidates;
  if(result.kind==='exact'){await choose(candidates[0]);return;}
  message=result.kind==='ambiguous'?'同じ番号に複数の仕様があります。カードを確認してください。':result.kind==='suggestions'?'近い番号が見つかりました。番号を確認してください。':result.kind==='unreadable'?'カード番号を読み取れませんでした。もう一度番号を枠内に合わせてください。':result.kind==='tooMany'?'仕様の追加確認が必要です。番号を読み直してください。':'登録されているカードに一致する番号がありません。番号を確認してください。';draw();
 }
 function zoomControls(){const z=cameraControl.zoomInfo();return `<div class="scan-zoom"><span>倍率 ${z.value.toFixed(1)}×</span>${z.supported?`<input type="range" aria-label="カメラ倍率" data-scan-zoom min="${z.min}" max="${z.max}" step="${z.step}" value="${z.value}" ${reading||z.busy||cameraPending?'disabled':''}>`:''}</div>`;}
 async function readCamera(){if(!root||reading||busy||stage!=='scan'||!stream||cameraPending)return;reading=true;ocrSource=true;message='';candidates=[];draw();const token=revision,samples=[];
  try{await DCBOCR.prepare();if(token!==revision||!root||document.hidden)return;const started=performance.now();for(let attempt=0;attempt<5;attempt++){
   const delay=Math.max(0,started+attempt*400-performance.now());if(delay)await new Promise(resolve=>{ocrResolve=resolve;ocrTimer=setTimeout(()=>{ocrResolve=null;resolve();},delay);});
   if(token!==revision||!root||document.hidden)return;if(attempt>0&&performance.now()-started>2200)break;
   const video=root.querySelector('video'),image=DCBOCR.crop(video,root.querySelector('.scan-camera').getBoundingClientRect(),root.querySelector('.scan-guide').getBoundingClientRect(),{pattern:DCBOCR.patterns[attempt]});
   const result=await DCBOCR.readNumber({image});if(token!==revision||!root||document.hidden)return;
   const match=DCBMatcher.match(result.text,DCBData.cards);DCBOCR.debugResult(result,match,image.ocrMeta);samples.push({...result,match});input=result.text.trim().slice(0,40);
  }
  if(token!==revision||!root)return;reading=false;const summary=DCBOCRConsensus.summarize(samples,DCBData.cards);DCBOCR.debugConsensus(summary);candidates=summary.candidates;
  if(mode==='fast'&&summary.auto){const card=summary.winner;if(!DCBOCRPolicy.available(card.id)){candidates=[];message='同じカードを続けて読み取りました。カードを替えるか、少し待ってから再読み取りしてください。';draw();return;}selected=card;candidates=[];await register(null);return;}
  message=candidates.length?(summary.ranked[0].confidence<80?'候補があります。読み取りが不確かです。番号を確認するか、再読み取りしてください。':'候補があります。カード名・番号・仕様を確認してください。'):'カード番号を確認してください。';draw();
  }catch(e){if(token!==revision||!root)return;reading=false;candidates=samples.length?DCBOCRConsensus.summarize(samples,DCBData.cards).candidates:[];message=candidates.length?'候補があります。読み取りを完了できませんでした。確認するか手入力で続けられます。':'カード番号を確認してください。再読み取りするか、手入力で続けられます。';if(['localhost','127.0.0.1'].includes(location.hostname))console.warn('[DCBOCR]',e.name,e.message);draw();}
 }
 async function choose(card){if(ocrSource&&!DCBOCRPolicy.available(card.id)){message='同じカードは少し待ってから再登録してください。';draw();return;}selected=card;candidates=[];message='';if(mode==='fast')await register(null);else{scanZoom=cameraControl.zoomInfo().value;stage='capture';draw();await cameraControl.setZoom(Math.max(cameraControl.zoomInfo().min,Math.min(cameraControl.zoomInfo().max,1)));if(root&&stage==='capture'&&stream)capture(true);}}
 const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 function liveFrame(){return DCBCapture.frame(root.querySelector('video'),root.querySelector('.scan-camera').getBoundingClientRect(),root.querySelector('.scan-guide').getBoundingClientRect());}
 async function capture(automatic=false){if(busy||autoPending||!root||stage!=='capture'||cameraPending)return;if(retakeId&&!stream){cameraMessage='カメラを起動してから撮影してください。';draw();return;}const token=++captureRevision;autoPending=true;cameraMessage=automatic?'カード全体を枠に合わせてください…':'撮影しています…';draw();const active=()=>token===captureRevision&&root&&stage==='capture'&&!document.hidden;
  try{const frames=[];if(stream){if(automatic){const start=performance.now();let previous=null,stable=0;while(active()){const image=liveFrame(),a=DCBCapture.analyze(image);stable=DCBCapture.motion(previous,a.signature)<5?stable+1:0;previous=a.signature;const elapsed=performance.now()-start;if(elapsed>=1500&&stable>=2)break;if(elapsed>=5500)break;await pause(250);}if(!active())return;cameraMessage='撮影しています…';draw();}
   for(let i=0;i<(automatic?5:1);i++){if(!active())return;const image=liveFrame();frames.push({image,analysis:DCBCapture.analyze(image)});if(automatic&&i<4)await pause(250);}
  }else{const image=document.createElement('canvas');image.width=420;image.height=600;const ctx=image.getContext('2d');ctx.fillStyle='#fff3f8';ctx.fillRect(0,0,420,600);ctx.fillStyle=selected.color;ctx.textAlign='center';ctx.font='24px sans-serif';ctx.fillText(selected.name,210,280);frames.push({image,analysis:DCBCapture.analyze(image)});}
  if(!active())return;const winner=DCBCapture.best(frames),image=DCBCapture.trim(winner),blob=await DCBCapture.blob(image);if(!active())return;clearPreview();pendingPhoto=blob;previewURL=URL.createObjectURL(blob);autoPending=false;stage='preview';cameraMessage='';draw();if(location.hostname==='localhost')console.debug('[DCBCapture]',{frames:frames.length,detected:winner.analysis.detected,score:winner.analysis.score,width:image.width,height:image.height});
  }catch(e){if(!active())return;autoPending=false;cameraMessage=e.message||'撮影できませんでした。もう一度お試しください。';draw();}}
 async function confirmPhoto(){if(busy||!pendingPhoto||stage!=='preview')return;if(!retakeId){await register(pendingPhoto);return;}busy=true;draw();const token=revision,cardId=retakeId,blob=pendingPhoto;try{await DCBPhotos.write({cardId,blob,capturedAt:Date.now()});if(token!==revision||!root)return;busy=false;clearPreview();location.hash='#card/'+cardId;}catch{if(token!==revision||!root)return;busy=false;cameraMessage='写真を保存できませんでした。もう一度お試しください。';draw();}}
 async function retakePhoto(){if(busy||!selected)return;cancelCapture();clearPreview();stage='capture';cameraMessage='';draw();if(stream)capture(true);}
 async function register(blob){if(busy||!root||!selected)return;const card=selected;const current=DCBStore.get(card);cancelCapture();if(current.ownedCount>=999){message='所持枚数が上限に達しています。';stage='scan';draw();return;}
  cancelCapture();busy=true;draw();const token=revision;let previous,photoWritten=false;
  try{
   if(blob){previous=await DCBPhotos.read(card.id);await DCBPhotos.write({cardId:card.id,blob,capturedAt:Date.now()});photoWritten=true;}
   if(token!==revision||!root)throw new Error('登録を中断しました。');
   if(DCBStore.get(card).ownedCount>=999)throw new Error('所持枚数が上限に達しています。');if(!DCBStore.update(card,{ownedCount:DCBStore.get(card).ownedCount+1}))throw new Error('所持情報を保存できませんでした。');
   if(ocrSource)DCBOCRPolicy.mark(card.id);recordRecent(card);clearPreview();busy=false;sessionCount++;stage='success';draw();clearTimeout(timer);timer=setTimeout(next,850);
  }catch(e){if(photoWritten){try{if(previous)await DCBPhotos.write(previous);else await DCBPhotos.remove(card.id);}catch{}}
   if(token!==revision||!root)return;busy=false;cameraMessage=blob?'写真または所持情報を保存できませんでした。再試行するか、写真なしで登録してください。':e.message;draw();}
 }
 function next(){if(!root||busy)return;cancelCapture();clearPreview();clearTimeout(timer);stage='scan';selected=null;candidates=[];message='';input='';cameraMessage='';draw();if(stream)cameraControl.setZoom(scanZoom);}
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&root){stopReading();cancelCapture();busy=false;cameraControl.stop('hidden');stream=null;if(autoPending){clearTimeout(timer);autoPending=false;busy=false;}if(root){cameraMessage='カメラを停止しました。再起動できます。';draw();}}});
 function handleClick(e){const button=e.target.closest('button');if(!button||!root?.contains(button))return;
  if(button.dataset.recentCard){if(busy)return;preserveNext=!retakeId;stop();location.hash='#card/'+button.dataset.recentCard;return;}
  if(button.dataset.mode){if(!busy&&!reading&&!autoPending&&!retakeId){clearTimeout(timer);cancelCapture();clearPreview();setMode(button.dataset.mode);stage='scan';selected=null;candidates=[];message='';draw();}return;}
  if(button.dataset.pick){if(!reading&&!busy){const card=candidates.find(c=>c.id===button.dataset.pick);if(card)choose(card);}return;}
  switch(button.dataset.scan){case 'ocr':readCamera();break;case 'manual':stopReading();ocrSource=false;draw();root.querySelector('#scan-number')?.focus();break;case 'stop-reading':stopReading();draw();break;case 'exit':if(!busy){const dest=retakeId?'#card/'+retakeId:'#binder';if(!retakeId)resume=null;stop();location.hash=dest;}break;case 'camera':camera();break;case 'retry':if(!busy){stopReading();next();}break;case 'next':next();break;case 'capture':capture(false);break;case 'without-photo':register(null);break;case 'confirm-photo':confirmPhoto();break;case 'retake-photo':retakePhoto();break;case 'auto':capture(true);break;case 'cancel-capture':cancelCapture();cameraMessage='';draw();break;case 'history':preserveNext=true;stop();location.hash='#register/history';break;case 'history-back':location.hash='#register';break;}

 }
 // Keep the mount for a back-forward-cache return; the shared camera already stops tracks.
 window.addEventListener('pagehide',()=>{stopReading();cancelCapture();clearTimeout(timer);autoPending=false;busy=false;reading=false;});
 window.addEventListener('pageshow',e=>{if(e.persisted&&root)draw();});document.addEventListener('click',handleClick);
 document.addEventListener('change',e=>{if(e.target.hasAttribute('data-scan-zoom')&&root?.contains(e.target)&&!reading){cameraControl.setZoom(Number(e.target.value));}});
 document.addEventListener('submit',e=>{if(e.target.id==='scan-number-form'&&root?.contains(e.target)){e.preventDefault();read();}});
 return{mount,stop,getMode,setMode};
})();




