const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function harness(){const listeners={},logs=[],winListeners={};const track={readyState:'live',stop(){this.readyState='ended';},addEventListener(){}};const stream={getTracks:()=>[track],getVideoTracks:()=>[track]};const video={isConnected:true,paused:true,srcObject:null,setAttribute(){},pause(){this.paused=true;},async play(){this.paused=false;}};const context={window:{isSecureContext:true,addEventListener:(n,f)=>winListeners[n]=f},document:{hidden:false,addEventListener:(n,f)=>listeners[n]=f},navigator:{mediaDevices:{getUserMedia:async()=>stream}},DOMException,console:{warn:(...args)=>logs.push(args),info(){}}};vm.runInNewContext(fs.readFileSync('camera.js','utf8'),context);const camera=context.window.DCBCamera.create();return {context,camera,video,stream,track,listeners,winListeners,logs};}
(async()=>{
 let h=harness(),calls=[];h.context.navigator.mediaDevices.getUserMedia=async c=>{calls.push(c);if(calls.length===1)throw new DOMException('rear unavailable','OverconstrainedError');return h.stream;};await h.camera.start(h.video);assert.equal(calls.length,2);assert.equal(calls[0].video.facingMode.ideal,'environment');assert.equal(calls[1].video,true);assert.equal(calls[1].audio,false);assert.equal(h.video.srcObject,h.stream);assert(h.video.muted&&h.video.playsInline&&h.video.autoplay);h.camera.stop();assert.equal(h.track.readyState,'ended');assert.equal(h.video.srcObject,null);
 for(const name of ['NotAllowedError','NotFoundError','NotReadableError','SecurityError','AbortError','Error']){h=harness();let count=0;h.context.navigator.mediaDevices.getUserMedia=async()=>{count++;throw new DOMException('test failure',name);};await h.camera.start(h.video);assert.equal(h.camera.state().error.name,name);assert(h.camera.state().error.message);assert.equal(count,['NotAllowedError','SecurityError'].includes(name)?1:2);assert(h.logs.some(args=>args.includes(name)&&args.includes('test failure')));h.context.navigator.mediaDevices.getUserMedia=async()=>h.stream;await h.camera.start(h.video);assert.equal(h.camera.state().error,null);assert.equal(h.camera.state().stream,h.stream);}
 for(const condition of ['secure','devices','method','policy']){h=harness();let calls=0;h.context.navigator.mediaDevices.getUserMedia=async()=>{calls++;return h.stream;};if(condition==='secure')h.context.window.isSecureContext=false;if(condition==='devices')delete h.context.navigator.mediaDevices;if(condition==='method')delete h.context.navigator.mediaDevices.getUserMedia;if(condition==='policy')h.context.document.permissionsPolicy={allowsFeature:()=>false};await h.camera.start(h.video);assert.equal(calls,0);assert.equal(h.camera.state().error.name,'SecurityError');}
 h=harness();h.video.play=async()=>{throw new DOMException('gesture required','NotAllowedError');};await h.camera.start(h.video);assert.equal(h.track.readyState,'ended');assert.match(h.camera.state().error.message,/映像を再生/);
 h=harness();let resolve;h.context.navigator.mediaDevices.getUserMedia=()=>new Promise(r=>resolve=r);const pending=h.camera.start(h.video);await h.camera.start(h.video);h.camera.stop();resolve(h.stream);await pending;assert.equal(h.track.readyState,'ended');assert.equal(h.camera.state().stream,null);
 h=harness();await h.camera.start(h.video);h.context.document.hidden=true;h.listeners.visibilitychange();assert.equal(h.track.readyState,'ended');assert.equal(h.camera.state().pending,false);
 h=harness();await h.camera.start(h.video);h.winListeners.pagehide();assert.equal(h.track.readyState,'ended');
 h=harness();await h.camera.start(h.video);const another=h.context.window.DCBCamera.create();const otherTrack={stop(){this.stopped=true;},addEventListener(){}};h.context.navigator.mediaDevices.getUserMedia=async()=>({getTracks:()=>[otherTrack],getVideoTracks:()=>[otherTrack]});await another.start({...h.video,srcObject:null});assert.equal(h.track.readyState,'ended');assert.equal(h.camera.state().stream,null);another.stop();assert(otherTrack.stopped);
 h=harness();let zoomValue=1,applied=[],requested;h.track.getCapabilities=()=>({zoom:{min:1,max:3,step:.1}});h.track.getSettings=()=>({zoom:zoomValue});h.track.getConstraints=()=>({width:{ideal:1920},height:{ideal:1080}});h.track.applyConstraints=async c=>{applied.push(c);zoomValue=c.advanced.at(-1).zoom;};h.context.navigator.mediaDevices.getUserMedia=async c=>{requested=c;return h.stream;};const zoomCamera=h.context.window.DCBCamera.create(undefined,{highResolution:true,defaultZoom:1.5});await zoomCamera.start(h.video);assert.equal(requested.video.width.ideal,1920);assert.equal(requested.video.height.ideal,1080);assert.equal(zoomCamera.zoomInfo().value,1.5);assert.equal(zoomCamera.zoomInfo().base,1);await zoomCamera.setZoom(99);assert.equal(zoomCamera.zoomInfo().value,3);assert.equal(applied.at(-1).width.ideal,1920);await zoomCamera.setZoom(-10);assert.equal(zoomCamera.zoomInfo().value,1);h.track.applyConstraints=async()=>{throw new DOMException('Zoom unavailable','OverconstrainedError');};assert.equal(await zoomCamera.setZoom(2),false);assert.equal(zoomCamera.zoomInfo().supported,false);assert.equal(h.track.readyState,'live');zoomCamera.stop();
 h=harness();await h.camera.start(h.video);assert.equal(h.camera.zoomInfo().supported,false);assert.equal(await h.camera.setZoom(2),false);assert.equal(h.track.readyState,'live');h.camera.stop();
 console.log('PASS: relaxed constraints/fallback, errors/logging/retry, HTTPS/API/policy checks, inline muted playback, play rejection cleanup, pending cancellation, hidden/pagehide and exclusive camera ownership, native zoom range/steps/failure and preserved resolution.');
})().catch(e=>{console.error(e);process.exitCode=1;});
