const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const cards=JSON.parse(fs.readFileSync('data/cards.json','utf8')),coordinates=JSON.parse(fs.readFileSync('data/coordinates.json','utf8')),news=JSON.parse(fs.readFileSync('data/news.json','utf8')),saved=new Map([['aikatsu-dcb-v01',JSON.stringify({'bloom-0':{ownedCount:99,memo:'legacy'}})],['dcb-trade-wants-v01','["bloom-0"]']]);const ctx={window:{},Date,crypto:{randomUUID},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('data.js','utf8'),ctx);ctx.DCBData=ctx.window.DCBCreateData({cards,coordinates,news});ctx.window.DCBData=ctx.DCBData;for(const file of ['store.js','matcher.js','binder.js','trade-model.js']){vm.runInContext(fs.readFileSync(file,'utf8'),ctx);Object.assign(ctx,ctx.window);}
const S=ctx.DCBStore,M=ctx.DCBTradeModel,B=ctx.DCBBinder,matcher=ctx.DCBMatcher;assert.equal(cards.length,139);assert.equal(new Set(cards.map(c=>c.id)).size,139);assert(cards.every(c=>S.get(c).ownedCount===0));assert.equal(M.offers().length,0);assert.equal(M.wants().length,0);assert.equal(cards.filter(c=>!c.cardNumber).length,2);const concrete=cards.filter(c=>c.coordinateName.trim()&&!['未確認','該当なし'].includes(c.coordinateName));const names=[...new Set(concrete.map(c=>c.coordinateName))];assert.equal(coordinates.length,23);assert.deepEqual(coordinates.map(c=>c.name).sort(),names.sort());assert.equal(cards.filter(c=>c.coordinateName==='未確認').length,46);assert(coordinates.some(c=>c.cardIds.length===3));assert(coordinates.some(c=>c.cardIds.length===4));assert(cards.filter(c=>c.coordinateName==='未確認').every(c=>!c.coordinateId));assert(cards.filter(c=>c.coordinateStatus.includes('未検証')).every(c=>c.coordinateId));assert(cards.filter(c=>c.coordinateName==='該当なし'||!c.coordinateName.trim()).every(c=>!c.coordinateId));for(const co of coordinates){assert.deepEqual([...co.cardIds].sort(),cards.filter(c=>c.coordinateName===co.name).map(c=>c.id).sort());assert.equal(co.name,co.masterName);}assert.equal(cards.find(c=>c.id==='DCB-0001').coordinateId,cards.find(c=>c.id==='DCB-0134').coordinateId);for(const co of coordinates)assert(co.cardIds.every(id=>cards.find(c=>c.id===id).coordinateId===co.id));assert(cards.every(c=>c.acquisitionType));assert.equal(cards.filter(c=>c.tradeRarity==='parallel').length,6);assert.equal(cards.filter(c=>c.rarity==='ER'&&c.tradeRarity==='encore').length,4);
const hit=matcher.match('E1-01',cards);assert.equal(hit.kind,'ambiguous');assert.equal(hit.candidates.length,2);assert.notEqual(hit.candidates[0].id,hit.candidates[1].id);assert.equal(matcher.match('TEST-01',cards).candidates.length,2);assert.equal(matcher.match('E1-02',cards).kind,'exact');assert.equal(matcher.match('',cards).kind,'unreadable');assert.equal(matcher.match('DEMO-001',cards).kind,'missing');
const c=cards[0],parallel=cards.find(x=>x.id==='DCB-0134');assert(S.update(c,{ownedCount:3,tradeCount:1,memo:'actual',favorite:true}));assert.equal(S.get(parallel).ownedCount,0);assert(S.update(parallel,{ownedCount:2,tradeCount:1}));assert.equal(M.scope({offers:['parallel']}).offers[0].id,parallel.id);assert.equal(M.scope({offers:['premium']}).offers[0].id,c.id);assert(M.changeWant(cards[1],true).ok);const q=M.session({offers:['parallel'],wants:['premium']});assert.equal(q.offers.length,1);assert.equal(q.wants.length,1);assert.equal(M.parse(JSON.stringify(q)).offers[0].id,parallel.id);assert(!JSON.stringify(q).includes('raw'));assert(!JSON.stringify(q).includes('memo'));assert.equal(JSON.parse(saved.get('aikatsu-dcb-v01'))['bloom-0'].memo,'legacy');assert.equal(B.pockets(cards,'number','keep',S).length,139);assert.equal(B.pockets(cards,'number','pack',S).length,2);for(const id of coordinates[0].cardIds)S.update(cards.find(c=>c.id===id),{ownedCount:1});assert.equal(B.progress(coordinates[0],cards,S),coordinates[0].cardIds.length);
console.log('PASS: actual 139-card Master, raw values and stable IDs, 23 Master-named variable-size coordinates, provisional names included, variants grouped by name, duplicate/blank numbers, variants, zero defaults, legacy separation, rarity scopes, trade payload and binder gaps.');

// Passes collect, save and trade by stable ID without becoming dress coordinates or rarities.
const passes=cards.filter(c=>c.cardKind==='アイカツパス（データセーブカード）');assert.equal(passes.length,2);assert(passes.every(c=>!c.cardNumber&&!c.coordinateId&&c.tradeRarity===null));assert(coordinates.every(co=>co.cardIds.every(id=>cards.find(c=>c.id===id).cardKind==='ドレスカード')));
assert.deepEqual(Array.from(ctx.DCBData.cardKinds,k=>k.value).sort(),[...new Set(cards.map(c=>c.cardKind))].sort());assert.equal(ctx.DCBData.cardKinds.find(k=>k.value===passes[0].cardKind).label,'アイカツパス');
assert(S.update(passes[0],{ownedCount:3}));assert(M.addOffer(passes[0]).ok);assert(M.changeWant(passes[1],true).ok);
const passScope={cardKind:passes[0].cardKind,offers:[],wants:[]};assert.equal(M.scope(passScope).offers.length,1);assert.equal(M.scope(passScope).wants.length,1);assert(!M.scope({offers:['normal'],wants:['premium']}).offers.some(c=>passes.includes(c)));assert(!M.scope({offers:['normal'],wants:['premium']}).wants.some(c=>passes.includes(c)));
const passSession=M.session(passScope),passPayload=M.parse(JSON.stringify(passSession));assert.equal(passPayload.filters.cardKind,passes[0].cardKind);assert.equal(passPayload.offers[0].id,passes[0].id);assert.equal(passPayload.wants[0].id,passes[1].id);assert.equal(M.match(M.parse(JSON.stringify(M.demo(passScope))),passScope).total,2);
const future=ctx.window.DCBCreateData({cards:[{id:'test-future',name:'テスト用の将来種別',cardKind:'検証用新種別'}],coordinates:[],news:[]});assert.equal(future.cardKinds[0].value,'検証用新種別');
console.log('PASS: 2 collectible passes, dynamic card kinds, no dress-coordinate membership, ownership/surplus, wants/offers, no rarity coercion, typed QR payload and bilateral matching, future card-kind option.');
