window.DCBTrade=(()=>{
 const M=DCBTradeModel;let ui,filters={offers:[],wants:[],cardKind:''},chipScroll={offers:0,wants:0},scanMounted=false,lastView=null,generated=null,peer=null,search='',message='',stream=null;
 const cameraControl=DCBCamera.create(state=>{stream=state.stream;const video=document.getElementById('trade-video');if(!video)return;message=state.error?.message||'';let status=document.getElementById('trade-camera-status');if(!status){status=document.createElement('p');status.id='trade-camera-status';status.className='trade-message';status.setAttribute('role','status');video.closest('.trade-camera').after(status);}status.textContent=message;status.hidden=!message;const retry=document.querySelector('[data-trade=camera]');if(retry){retry.disabled=state.pending;retry.textContent=state.pending?'カメラを起動中…':state.error&&state.error.name!=='Stopped'?'もう一度試す':'カメラを起動';}});
 const titles={offers:'交換候補カード', 'add-offer':'交換候補を追加',wants:'ほしいカード','add-want':'ほしいカードを追加',qr:'自分のQR',scan:'QRを読み取る',matches:'交換候補'};
 const title=view=>titles[view]||'トレード';
 const go=view=>{message='';search='';const hash='#trade'+(view?'/'+view:'');if(location.hash===hash)ui.render();else location.hash=hash;};
 const button=(label,action,role='secondary',extra='',modifier='')=>`<button type="button" class="btn-${role} ${modifier}" data-trade="${action}" ${extra}>${DCBUI.icon(label==='戻る'?'':{scan:'camera',show:'qr-show'}[action],'button-icon')}${label}</button>`;
 const note='<p class="trade-note">交換前に、実物のカードと内容を必ず確認してください。</p>';
 function rarityChip(side,type){return `<button type="button" class="btn-secondary btn-compact rarity-chip" data-trade-rarity="${type.id}" data-side="${side}" aria-pressed="${type.id==='all'?!filters[side].length:filters[side].includes(type.id)}">${type.label}</button>`;}
 const supportsRarity=()=>!filters.cardKind||DCBData.cards.some(c=>c.cardKind===filters.cardKind&&DCBData.isDressCard(c));
 const kindFilter=(header=false)=>DCBData.cardKinds.length?`<label class="${header?'trade-header-kind':'trade-kind-filter'}">カード種別<select class="ui-select" data-trade-kind><option value="">すべて</option>${DCBData.cardKinds.map(k=>`<option value="${ui.esc(k.value)}" ${filters.cardKind===k.value?'selected':''}>${ui.esc(k.label)}</option>`).join('')}</select></label>`:'';
 function allRarities(side){if(!supportsRarity())return '';return rarityChip(side,{id:'all',label:'すべて'});}
 function chips(side){if(!supportsRarity())return '';return `<div class="trade-rarity-chips" data-rarity-side="${side}" role="group" aria-label="${side==='offers'?'交換に出せるカード':'ほしいカード'}のレア度">${M.rarityTypes.map(type=>rarityChip(side,type)).join('')}</div>`;}
 function canShowQR(){const selected=M.scope(filters);return selected.offers.length+selected.wants.length>0;}
 function summary(){return `<div class="trade-qr-actions">${button('QRを読み取る','scan','secondary','','btn-tile')}${button('QRを表示','show','primary',canShowQR()?'':'disabled','btn-tile')}</div><p class="trade-note">交換前に実物のカードを確認してください。</p><section class="trade-section"><div class="trade-heading"><h2>交換に出せるカード</h2><div class="trade-heading-actions">${allRarities('offers')}<span class="trade-registration-count">${M.offers().length} / 50</span></div></div>${chips('offers')}<div class="trade-section-actions">${button('カードを見る','offers')}${button('＋追加する','add-offer','primary')}</div></section><section class="trade-section"><div class="trade-heading"><h2>ほしいカード</h2><div class="trade-heading-actions">${allRarities('wants')}<span class="trade-registration-count">${M.wants().length} / 50</span></div></div>${chips('wants')}<div class="trade-section-actions">${button('カードを見る','wants')}${button('＋追加する','add-want','primary')}</div></section>`;}
 function tile(c,count,actions=''){return `<article class="trade-card"><button class="trade-card-image" data-trade="detail" data-id="${c.id}" aria-label="${ui.esc(c.name)} ${c.cardNumber}"><span class="trade-art-wrap">${ui.art(c,false)}${count?`<span class="inventory-badge">×${count}</span>`:''}</span><span class="card-number">${ui.esc(c.cardNumber||c.name)}</span></button>${actions}</article>`;}
 function list(view){const adding=view.startsWith('add-'),offer=view.includes('offer');let items=offer?(adding?DCBData.cards.filter(c=>M.remaining(c)>0):M.offers()):(adding?DCBData.cards.filter(c=>!M.wants().some(w=>w.id===c.id)).sort((a,b)=>(DCBStore.get(a).ownedCount>0)-(DCBStore.get(b).ownedCount>0)||a.cardNumber.localeCompare(b.cardNumber)):M.wants());
 items=items.filter(c=>(!filters.cardKind||c.cardKind===filters.cardKind)&&[c.name,c.cardNumber,c.brand,c.specification,c.character].join(' ').toLowerCase().includes(search.toLowerCase()));const current=offer?M.offers().length:M.wants().length;
 return `<div class="trade-list-heading"><span>${current} / 50</span>${button(offer?'交換候補を見る':'ほしいカードを見る',offer?'offers':'wants','text')}</div><label class="search trade-search"><input class="ui-input" id="trade-search" aria-label="トレードカードを検索" placeholder="カード名・番号・ブランドを検索" value="${ui.esc(search)}"></label>${kindFilter()}<div id="trade-list-results">${listResults(items,adding,offer,current)}</div>`;
 }
 function listResults(items,adding,offer,current){return items.length?`<div class="trade-grid">${items.map(c=>{const count=offer?DCBStore.get(c).tradeCount:0;let actions='';if(adding){const full=current>=50&&(!offer||!count);actions=`${offer?`<span class="trade-remaining">あと${M.remaining(c)}枚</span>`:''}${button('＋ 追加',offer?'add-offer-card':'add-want-card','primary',`data-id="${c.id}" ${full?'disabled':''}`)}`;}else if(offer){actions=`<div class="trade-count-edit">${button('−','decrease','text',`data-id="${c.id}" aria-label="${ui.esc(c.cardNumber||c.name)}の交換枚数を減らす"`)}<span>×${count}</span>${button('＋','add-offer-card','text',`data-id="${c.id}" ${M.remaining(c)?'':'disabled'} aria-label="${ui.esc(c.cardNumber||c.name)}の交換枚数を増やす"`)}</div>`;}else{actions=button('削除','remove-want','text',`data-id="${c.id}"`);}return tile(c,count,actions);}).join('')}</div>`:`<p class="trade-empty">${adding?(offer?'追加できる余剰カードはありません。':'追加できるカードはありません。'):'登録したカードはありません。'}</p>`;}
 function counts(items){return `<dl class="trade-counts"><div><dt>交換に出せるカード</dt><dd>${items.offers.length}<span>種類</span></dd></div><div><dt>ほしいカード</dt><dd>${items.wants.length}<span>種類</span></dd></div></dl>`;}
 function dummyQR(session){let seed=0;for(const ch of session.sessionId)seed=(seed*31+ch.charCodeAt(0))>>>0;const cells=[];const finder=(x,y)=>{for(let dx=0;dx<7;dx++)for(let dy=0;dy<7;dy++)if(dx===0||dy===0||dx===6||dy===6||(dx>=2&&dx<=4&&dy>=2&&dy<=4))cells.push(`<rect x="${x+dx}" y="${y+dy}" width="1" height="1"/>`);};finder(0,0);finder(18,0);finder(0,18);for(let y=0;y<25;y++)for(let x=0;x<25;x++){if((x<8&&y<8)||(x>16&&y<8)||(x<8&&y>16))continue;seed=(Math.imul(seed,1664525)+1013904223)>>>0;if(seed&0x80000000)cells.push(`<rect x="${x}" y="${y}" width="1" height="1"/>`);}return `<svg viewBox="-3 -3 31 31" role="img" aria-label="デモ専用のダミーQR"><rect x="-3" y="-3" width="31" height="31" fill="white"/><g fill="#303239">${cells.join('')}</g></svg>`;}
 function qr(){if(!generated)generated=M.session(filters);return `<div class="trade-qr">${dummyQR(generated)}<p>ダミーQR（V0.1）</p><small>有効期限：${new Date(generated.expiresAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</small></div>${counts(generated)}<div class="trade-bottom-actions">${button('戻る','home')}</div>`;}
 function scan(){return `<div class="trade-camera"><video id="trade-video" autoplay muted playsinline aria-label="QR読み取り用カメラ"></video><span>QR読み取りプレビュー</span></div><div class="trade-bottom-actions">${button('カメラを起動','camera')}${button('ダミーQRを読み込む','demo','primary')}</div>`;}
 function matches(){if(!peer)return button('QRを読み取る','scan','primary');if(peer.expiresAt<=Date.now())return `<p class="trade-empty">有効期限が切れています。</p>${button('QRを読み取る','scan','primary')}`;const result=M.match(peer,filters);return `<p class="trade-match-heading">${result.total?`交換候補が${result.total}件見つかりました`:'今回は交換候補が見つかりませんでした'}</p>${result.total?`${result.give.length?`<section class="trade-section"><h2>あなたが渡せる</h2><div class="trade-grid">${result.give.map(item=>tile(item.card,item.count)).join('')}</div></section>`:''}${result.receive.length?`<section class="trade-section"><h2>相手からもらえる</h2><div class="trade-grid">${result.receive.map(item=>tile(item.card,item.count)).join('')}</div></section>`:''}${note}<label class="trade-check"><input type="checkbox" id="trade-confirmed">双方で実物と交換内容を確認しました</label>${button('確認を終える','finish','primary','disabled')}`:''}<div class="trade-bottom-actions">${button('別の相手のQRを読み取る','scan')}${button('条件を選び直す','home')}</div>`;}
 function screen(view){if(['scope','confirm'].includes(view)){history.replaceState(null,'',location.pathname+location.search+'#trade');view='';}const nextView=view||'';if(lastView!==nextView)message='';lastView=nextView;const content=view==='offers'||view==='add-offer'||view==='wants'||view==='add-want'?list(view):view==='qr'?qr():view==='scan'?scan():view==='matches'?matches():summary();return `<div class="trade-page" data-trade-view="${view||''}">${message?`<p class="trade-message" role="status">${ui.esc(message)}</p>`:''}${content}</div>`;}
 function stopCamera(){cameraControl.stop();stream=null;}
 function camera(){const video=document.getElementById('trade-video');if(video)cameraControl.start(video);}
 function read(raw){try{peer=M.parse(raw);go('matches');}catch(error){message=error.message;ui.render();}}
 function configure(config){ui=config;document.getElementById('app').addEventListener('click',async e=>{const chip=e.target.closest('[data-trade-rarity]');if(chip&&chip.closest('.trade-page')){const side=chip.dataset.side,id=chip.dataset.tradeRarity;chipScroll[side]=document.querySelector(`[data-rarity-side="${side}"]`)?.scrollLeft||0;filters[side]=id==='all'?[]:filters[side].includes(id)?filters[side].filter(value=>value!==id):[...filters[side],id];ui.render();return;}const target=e.target.closest('[data-trade]');if(!target||!target.closest('.trade-page'))return;const action=target.dataset.trade,c=DCBData.cards.find(c=>c.id===target.dataset.id);if(['home','offers','wants','add-offer','add-want','scan'].includes(action)){go(action==='home'?'':action);return;}if(action==='detail'){location.hash='#card/'+c.id;return;}if(action==='camera'){camera();return;}if(action==='demo'){read(JSON.stringify(M.demo(filters)));return;}if(action==='show'){if(!canShowQR())return;generated=M.session(filters);go('qr');return;}if(action==='finish'){if(!document.getElementById('trade-confirmed')?.checked)return;if(peer?.expiresAt<=Date.now()){message='有効期限が切れています。';ui.render();return;}peer=null;go('');ui.toast('内容の確認を終えました');return;}let result;if(action==='add-offer-card')result=M.addOffer(c);if(action==='decrease')result={ok:DCBStore.update(c,{tradeCount:Math.max(0,DCBStore.get(c).tradeCount-1)})};if(action==='add-want-card'||action==='remove-want')result=M.changeWant(c,action==='add-want-card');if(result){message=result.ok?'':result.error||'保存できませんでした。';ui.render();}});
 document.getElementById('app').addEventListener('change',e=>{if(!e.target.closest('.trade-page')&&!e.target.hasAttribute('data-trade-kind'))return;if(e.target.hasAttribute('data-trade-kind')){filters.cardKind=e.target.value;filters.offers=[];filters.wants=[];ui.render();return;}if(e.target.id==='trade-confirmed')document.querySelector('[data-trade="finish"]').disabled=!e.target.checked;});
 document.getElementById('app').addEventListener('input',e=>{if(e.target.id!=='trade-search')return;search=e.target.value;const start=e.target.selectionStart;ui.render();const input=document.getElementById('trade-search');input.focus();input.setSelectionRange(start,start);});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)cameraControl.stop('hidden');});window.addEventListener('pagehide',stopCamera);
 }
 function afterRender(view){if(view===null){message='';lastView=null;}document.querySelectorAll('.trade-rarity-chips').forEach(el=>el.scrollLeft=chipScroll[el.dataset.raritySide]||0);if(view==='scan'){if(!scanMounted){scanMounted=true;camera();}}else scanMounted=false;}
 return {configure,screen,title,stopCamera,afterRender,headerAction:()=>kindFilter(true)};
})();
