const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const go=async hash=>{await page.evaluate(hash=>location.hash=hash,hash);await page.waitForTimeout(100);};
 await page.goto('http://localhost:4174/app/#binder');await page.evaluate(()=>DCBReady);await page.locator('.opening').waitFor({state:'detached'});
 const kind=await page.evaluate(()=>DCBData.cards.find(c=>c.id==='DCB-0140').cardKind),entry=id=>page.locator('[data-go="#card/'+id+'"]');
 assert.equal(await page.locator('.binder-card').count(),139);await page.getByRole('button',{name:'絞り込み',exact:false}).click();await page.locator('[data-filter=cardKind]').selectOption(kind);assert.equal(await page.locator('.binder-card').count(),2);
 assert.equal(await entry('DCB-0140').locator('.card-name').textContent(),'アイカツパス（標準デザイン）');assert.deepEqual(await entry('DCB-0140').locator('.card-number').allTextContents(),['標準パス・星形ロゴ','2026.08.29']);assert(!await page.locator('#results').innerText().then(t=>/DCB-\d+|該当なし/.test(t)));
 await page.getByRole('button',{name:'絞り込み',exact:false}).click();await page.screenshot({path:'pass-grid.png'});await page.getByRole('button',{name:'絞り込み',exact:false}).click();await page.getByRole('button',{name:'リスト表示',exact:true}).click();assert.match(await entry('DCB-0141').locator('.card-number').textContent(),/商品付属限定パス　2026-10上旬/);
 await page.locator('[data-filter=cardKind]').selectOption('');await page.locator('#search').fill('星形ロゴ');assert.equal(await page.locator('.binder-row').count(),1);await page.locator('#search').fill('アイカツパス');assert.equal(await page.locator('.binder-row').count(),2);
 await entry('DCB-0140').click();assert.equal(await page.locator('.details .eyebrow').count(),0);assert.equal(await page.locator('[data-go^="#coordinate/"]').count(),0);assert.match(await page.locator('.details').innerText(),/標準パス・星形ロゴ/);assert.match(await page.locator('.details').innerText(),/東京おもちゃショー2026/);assert(!await page.locator('.details').innerText().then(t=>/DCB-\d+/.test(t)));
 for(let i=0;i<3;i++)await page.getByRole('button',{name:'所持枚数を増やす',exact:true}).click();assert.equal(await page.evaluate(()=>DCBStore.get(DCBData.cards.find(c=>c.id==='DCB-0140')).ownedCount),3);
 await page.evaluate(async()=>{await DCBPhotos.write({cardId:'DCB-0140',blob:new Blob(['<svg xmlns="http://www.w3.org/2000/svg" width="80" height="120"><rect width="80" height="120" fill="pink"/></svg>'],{type:'image/svg+xml'}),capturedAt:Date.now()});});
 await go('#binder');await page.getByRole('button',{name:'条件をクリア',exact:true}).click();await page.getByRole('button',{name:'グリッド表示',exact:true}).click();await page.locator('[data-filter=cardKind]').selectOption(kind);await entry('DCB-0140').locator('img').waitFor();assert.equal(await entry('DCB-0140').locator('.inventory-badge').textContent(),'×3');
 await page.getByRole('tab',{name:'コレクション / コーデ'}).click();assert.equal(await page.locator('.coord').count(),23);assert(!await page.locator('.coord-grid').innerText().then(t=>t.includes('アイカツパス')));
 await page.getByRole('tab',{name:'バインダーモード'}).click();await page.locator('[data-album-kind]').selectOption(kind);assert.equal(await page.locator('.album-card').count(),1);await page.locator('[data-binder-sort=album]').selectOption('number');assert.equal(await page.locator('.album-blank').count(),1);assert.equal(await page.locator('.album-card').count(),1);assert.equal(await page.locator('.album-grid').innerText(),'');await page.screenshot({path:'pass-album.png'});await page.locator('[data-album-gaps]').selectOption('pack');assert.equal(await page.locator('.album-blank').count(),0);
 await go('#trade/add-offer');await page.locator('[data-trade-kind]').selectOption(kind);assert.equal(await page.locator('.trade-card').count(),1);await page.locator('[data-trade="add-offer-card"][data-id="DCB-0140"]').click();
 await go('#trade/add-want');assert.equal(await page.locator('.trade-card').count(),2);await page.locator('[data-trade="add-want-card"][data-id="DCB-0141"]').click();await go('#trade');assert.equal(await page.locator('[data-trade-kind]').inputValue(),kind);assert.equal(await page.locator('.rarity-chip').count(),0);assert(await page.getByRole('button',{name:'QRを表示',exact:true}).isEnabled());await page.getByRole('button',{name:'QRを表示',exact:true}).click();await page.locator('.trade-qr').waitFor();assert.match(await page.locator('.trade-counts').innerText(),/1/);
 const payload=await page.evaluate(kind=>DCBTradeModel.session({cardKind:kind,offers:[],wants:[]}),kind);assert.deepEqual(payload.offers.map(c=>c.id),['DCB-0140']);assert.deepEqual(payload.wants.map(c=>c.id),['DCB-0141']);assert(!await page.locator('main').innerText().then(t=>/DCB-\d+/.test(t)));
 await page.reload();await page.evaluate(()=>DCBReady);await page.locator('.opening').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>DCBStore.get(DCBData.cards.find(c=>c.id==='DCB-0140')).ownedCount),3);assert.equal(await page.evaluate(()=>DCBTradeModel.wants().length),1);
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});for(const hash of ['#binder','#trade','#trade/add-offer','#card/DCB-0141']){await go(hash);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),width+' '+hash);}}
 for(const theme of ['white','dark'])for(const color of ['cute','cool','sexy','pop']){await page.evaluate(({theme,color})=>{DCBDisplay.set('theme',theme);DCBDisplay.set('color',color);},{theme,color});for(const hash of ['#card/DCB-0140','#trade/add-want']){await go(hash);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}assert.equal(await page.locator('[data-trade-kind] option').filter({hasText:'アイカツパス'}).count(),1);}
 await page.evaluate(()=>{DCBDisplay.set('theme','white');DCBDisplay.set('color','cute');});await page.setViewportSize({width:320,height:568});await go('#trade');assert(await page.locator('.trade-section:last-child .trade-section-actions').evaluate(el=>el.getBoundingClientRect().bottom<=document.querySelector('nav').getBoundingClientRect().top));await page.screenshot({path:'pass-trade-320.png'});
 assert.deepEqual(errors,[]);console.log('PASS: 2 pass cards, dynamic kind filters, names/specs/dates without numbers or IDs, design search, detailed source fields, ownership/photo/badge persistence, pass-only album/gaps, no coordinates, offers/wants/typed QR, four widths.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
