const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const path=require('node:path'),assert=require('node:assert/strict');let browser;
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const url='file:///'+path.resolve('index.html').replaceAll('\\','/');
 await page.setViewportSize({width:390,height:844});await page.goto(url);await page.evaluate(()=>window.DCBReady);await page.locator('.opening-screen').waitFor();const initial=await page.locator('.opening .opening-logo').boundingBox();
 await page.locator('.opening-to-login').waitFor();await page.waitForTimeout(450);const middle=await page.locator('.opening .opening-logo').boundingBox();assert(middle.y<initial.y);const color=await page.locator('.opening .opening-logo').evaluate(e=>getComputedStyle(e).color);assert.notEqual(color,'rgb(255, 255, 255)');const opacity=await page.locator('.opening-screen').evaluate(e=>Number(getComputedStyle(e,'::after').opacity));assert(opacity>0&&opacity<1);await page.screenshot({path:'preview-login-transition.png'});
 await page.locator('.opening').waitFor({state:'detached'});assert.equal(await page.locator('.login-screen .opening-spark').count(),1);assert.equal(await page.locator('.login-screen').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');assert.equal(await page.locator('.login-logo').evaluate(e=>getComputedStyle(e).color),'rgb(255, 98, 167)');const final=await page.locator('.login-logo').boundingBox();const firstField=await page.locator('.login-field').first().boundingBox();assert(Math.abs(final.y+final.height/2-firstField.y/2)<1);await page.screenshot({path:'preview-login-mobile.png'});
 await page.getByRole('button',{name:'はじめての方 / アカウント作成',exact:true}).click();await page.getByRole('heading',{name:'アカウント作成',exact:true}).waitFor();assert.equal(await page.locator('.opening-spark').count(),1);await page.getByRole('button',{name:'ログイン画面に戻る',exact:true}).click();await page.locator('#login-form').waitFor();const id=page.getByRole('textbox',{name:'メールアドレスまたはコレクターID'}),password=page.locator('[name="password"]');assert.equal(await password.getAttribute('type'),'password');assert.equal(await page.locator('.login-screen input').count(),3);
 await page.getByRole('link',{name:'パスワードをお忘れの方'}).click();assert.equal(await page.evaluate(()=>location.hash),'#login');await page.locator('#toast.visible').waitFor();
 await page.getByRole('button',{name:'ログイン',exact:true}).click();assert.equal(await page.evaluate(()=>location.hash),'#login');
 await id.fill('collector-test');await password.fill('dummy-password-never-save');await page.getByRole('checkbox',{name:'ログインしたままにする'}).check();await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.locator('.home-view').waitFor();const saved=await page.evaluate(()=>JSON.stringify(localStorage));assert(!saved.includes('dummy-password-never-save'));assert(saved.includes('collector-test'));
 await page.getByRole('button',{name:'設定',exact:true}).click();await page.locator('[data-settings-go="user"]').click();await page.getByRole('button',{name:'ログイン画面に戻る'}).click();await id.waitFor();assert.equal(await id.inputValue(),'collector-test');assert(await page.getByRole('checkbox',{name:'ログインしたままにする'}).isChecked());assert.equal(await password.inputValue(),'');
 await page.getByRole('checkbox',{name:'ログインしたままにする'}).uncheck();await password.fill('dummy2');await page.getByRole('button',{name:'ログイン',exact:true}).click();await page.locator('.home-view').waitFor();await page.goto(url+'#login');await page.evaluate(()=>window.DCBReady);await id.waitFor();assert.equal(await id.inputValue(),'');
 for(const [width,height] of [[320,568],[390,844],[1440,1000]]){await page.setViewportSize({width,height});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const stage=await page.locator('.login-screen').boundingBox();assert.equal(stage.width,width>700?390:width);const form=await page.locator('.login-form').boundingBox();assert(form.y+form.height<=stage.y+stage.height);if(width===1440)await page.screenshot({path:'preview-login-desktop.png'});}
 const reduced=await browser.newContext({reducedMotion:'reduce'});const rp=await reduced.newPage();await rp.goto(url);await rp.locator('.opening').waitFor({state:'detached'});await rp.locator('#login-form').waitFor();assert.deepEqual(errors,[]);console.log('PASS: moving shared logo, color/background transition, one star, form validation, password masking/no storage, remember preference, forgot link, mobile/desktop layouts, reduced motion, no errors');await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});




