const fs=require('node:fs'),cp=require('node:child_process'),assert=require('node:assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');let browser;
const env={...process.env};delete env.SITE_URL;delete env.PUBLIC_INDEXING;delete env.VERCEL_ENV;delete env.VERCEL;delete env.VERCEL_URL;delete env.VERCEL_PROJECT_PRODUCTION_URL;
(async()=>{try{cp.execFileSync(process.execPath,['build.cjs'],{env:{...env,VERCEL_ENV:'production'},stdio:'pipe'});assert.fail('Missing production URL accepted');}catch(e){assert.match(String(e.stderr),/confirmed HTTPS SITE_URL/);}
// First deployment works without a manually chosen domain and stays unindexed.
cp.execFileSync(process.execPath,['build.cjs'],{env:{...env,VERCEL:'1',VERCEL_ENV:'production',VERCEL_PROJECT_PRODUCTION_URL:'dcb-phone-check.vercel.app',VERCEL_URL:'dcb-build-check.vercel.app'}});
assert.match(fs.readFileSync('dist/index.html','utf8'),/canonical" href="https:\/\/dcb-phone-check.vercel.app\//);
assert.match(fs.readFileSync('dist/index.html','utf8'),/noindex, follow/);
cp.execFileSync(process.execPath,['build.cjs'],{env:{...env,VERCEL:'1',VERCEL_ENV:'preview',VERCEL_URL:'dcb-preview-check.vercel.app'}});
assert.match(fs.readFileSync('dist/index.html','utf8'),/canonical" href="https:\/\/dcb-preview-check.vercel.app\//);
for(const host of ['localhost','dcb.example','example.com/path','user@example.com']){
  assert.throws(()=>cp.execFileSync(process.execPath,['build.cjs'],{env:{...env,VERCEL:'1',VERCEL_ENV:'production',VERCEL_URL:host},stdio:'pipe'}));
}
cp.execFileSync(process.execPath,['build.cjs'],{env:{...env,SITE_URL:'https://dcb.example.jp',PUBLIC_INDEXING:'true',VERCEL_ENV:'production'}});
const html=fs.readFileSync('dist/index.html','utf8');assert.match(html,/<link rel="canonical" href="https:\/\/dcb.example.jp\/">/);assert.match(html,/content="index, follow"/);const schema=JSON.parse(html.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)[1]);assert.equal(schema['@type'],'WebApplication');assert(!('aggregateRating' in schema));assert.match(fs.readFileSync('dist/robots.txt','utf8'),/Sitemap: https:\/\/dcb.example.jp\/sitemap.xml/);assert(!fs.readFileSync('dist/sitemap.xml','utf8').includes('/app'));assert.equal((fs.readFileSync('dist/sitemap.xml','utf8').match(/<url>/g)||[]).length,1);assert.match(fs.readFileSync('dist/news.html','utf8'),/noindex, follow/);assert.match(fs.readFileSync('dist/app/index.html','utf8'),/noindex, nofollow/);
cp.execFileSync(process.execPath,['build.cjs'],{env:{...env,SITE_URL:'https://dcb.example.jp',PUBLIC_INDEXING:'true',VERCEL_ENV:'preview'}});assert.match(fs.readFileSync('dist/index.html','utf8'),/noindex, follow/);cp.execFileSync(process.execPath,['build.cjs'],{env});
for(const name of ['README.md','css-cleanup-baseline.json','tests.cjs','server.cjs','package.json','.env']){assert(!fs.existsSync('dist/'+name));assert.equal((await fetch('http://localhost:4174/'+name)).status,404);}
assert.equal((await fetch('http://localhost:4174/missing-page')).status,404);assert.equal((await fetch('http://localhost:4174/app',{redirect:'manual'})).status,308);assert.equal((await fetch('http://localhost:4174/app/deep-link')).status,200);assert.match((await fetch('http://localhost:4174/app/')).headers.get('x-robots-tag'),/noindex/);assert.match((await fetch('http://localhost:4174/manifest.webmanifest')).headers.get('content-type'),/manifest\+json/);
const manifest=await (await fetch('http://localhost:4174/manifest.webmanifest')).json();assert.equal(manifest.start_url,'/app/');assert.equal(manifest.display,'standalone');for(const icon of manifest.icons)assert.equal((await fetch('http://localhost:4174'+icon.src)).status,200);
browser=await chromium.launch({channel:'msedge',headless:true});const errors=[];const noJS=await browser.newContext({javaScriptEnabled:false}),staticPage=await noJS.newPage();await staticPage.goto('http://localhost:4174/');assert.equal(await staticPage.locator('h1').count(),1);assert.match(await staticPage.locator('main').innerText(),/所持カード/);assert.match(await staticPage.locator('main').innerText(),/ダミーQR/);await noJS.close();const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
for(const size of [{width:320,height:568},{width:390,height:844},{width:1440,height:1000}]){await page.setViewportSize(size);await page.goto('http://localhost:4174/');await page.evaluate(()=>window.DCBReady);assert(await page.locator('h1').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.goto('http://localhost:4174/news');await page.evaluate(()=>window.DCBReady);assert.equal(await page.locator('.public-news-list li').count(),4);assert.match(await page.locator('main').innerText(),/ダミー/);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:4174/');await page.evaluate(()=>window.DCBReady);await page.screenshot({path:'public-top-mobile.png',fullPage:true});await page.getByRole('link',{name:'アイカツDCBを開く',exact:false}).first().click();await page.waitForURL('**/app/**');await page.locator('.login-screen').waitFor();await page.locator('.opening').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>location.hash),'#login');assert.equal(new URL(page.url()).pathname,'/app/');await page.evaluate(()=>{DCBStore.update(DCBData.cards[0],{ownedCount:5,memo:'publishing test'});DCBDisplay.set('color','cool');DCBDisplay.set('theme','dark');});await page.goto('http://localhost:4174/?preview=login#binder');await page.evaluate(()=>window.DCBReady);await page.waitForURL('**/app/**');await page.locator('[data-mode=cards]').waitFor();await page.locator('.opening').waitFor({state:'detached'});assert.equal(new URL(page.url()).pathname,'/app/');assert.equal(new URL(page.url()).search,'?preview=login');assert.equal(await page.evaluate(()=>location.hash),'#binder');assert.equal(await page.evaluate(()=>DCBStore.get(DCBData.cards[0]).ownedCount),5);assert.equal(await page.evaluate(()=>DCBDisplay.preferences.theme),'dark');await page.reload();await page.evaluate(()=>window.DCBReady);await page.locator('.opening').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>DCBStore.get(DCBData.cards[0]).memo),'publishing test');await page.goto('http://localhost:4174/app/?preview=login#trade/scope');await page.evaluate(()=>window.DCBReady);await page.locator('.opening').waitFor({state:'detached'});assert.equal(new URL(page.url()).pathname,'/app/');assert.equal(await page.evaluate(()=>location.hash),'#trade');assert.deepEqual(errors,[]);await browser.close();console.log('PASS: safe build, production/preview indexing, static HTML without JS, metadata, sitemap, excluded files, 404, manifest/icons, 3 responsive sizes, landing/opening/login, legacy links, same-origin storage/reload.');})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1;});
