const {chromium}=require(process.env.PLAYWRIGHT_PATH),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.tradeCameraRequests=0;navigator.mediaDevices.getUserMedia=async()=>{window.tradeCameraRequests++;const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;window.tradeTestStream=canvas.captureStream(5);return window.tradeTestStream;};});
 await page.goto('http://localhost:4173/?preview=login#trade');await page.evaluate(()=>window.DCBReady);await page.locator('.opening').waitFor({state:'detached'});
 assert.equal(await page.locator('.trade-qr-actions .btn-primary').count(),1);assert.equal(await page.locator('.trade-qr-actions .btn-primary').textContent(),'QRを表示');assert(await page.locator('[data-trade=show]').isDisabled());assert.equal(await page.locator('.trade-qr-actions .btn-secondary').count(),1);assert(!(await page.locator('.trade-page').innerText()).includes('QRを生成する'));
 const labels=['パラレル','プレミアム','アンコール','レア','ノーマル'];for(const side of ['offers','wants'])assert.deepEqual(await page.locator('[data-rarity-side='+side+'] button').allTextContents(),labels);
 await page.locator('[data-trade=scan]').click();await page.locator('#trade-video').waitFor();await page.waitForFunction(()=>document.getElementById('trade-video').srcObject);assert.equal(await page.evaluate(()=>window.tradeCameraRequests),1);
 await page.locator('nav [data-go="#trade"]').click();await page.locator('.trade-qr-actions').waitFor();assert.equal(await page.evaluate(()=>window.tradeTestStream.getVideoTracks()[0].readyState),'ended');
 await page.locator('[data-trade="add-offer"]').click();await page.locator('.trade-page[data-trade-view="add-offer"]').waitFor();const offerId=await page.locator('[data-trade="add-offer-card"]').first().getAttribute('data-id');const initial=await page.evaluate(id=>DCBStore.get(DCBData.cards.find(c=>c.id===id)).ownedCount,offerId);
 await page.locator('[data-trade="add-offer-card"][data-id="'+offerId+'"]').click();await page.locator('[data-trade="add-offer-card"][data-id="'+offerId+'"]').click();assert.equal(await page.locator('[data-trade="add-offer-card"][data-id="'+offerId+'"]').count(),0);await page.locator('[data-trade="offers"]').click();await page.locator('.trade-page[data-trade-view="offers"]').waitFor();assert.equal(await page.locator('.inventory-badge').textContent(),'×2');
 await page.locator('nav [data-go="#trade"]').click();await page.locator('[data-trade="add-want"]').click();const wantId=await page.locator('[data-trade="add-want-card"]').first().getAttribute('data-id');await page.locator('[data-trade="add-want-card"][data-id="'+wantId+'"]').click();await page.locator('[data-trade="wants"]').click();await page.locator('.trade-page[data-trade-view="wants"]').waitFor();assert.equal(await page.locator('.trade-card').count(),1);
 // Add an R card to each side; PR and R must filter independently.
 await page.evaluate(()=>{const c=DCBData.cards.find(c=>c.rarity==='R');DCBStore.update(c,{ownedCount:3});DCBTradeModel.addOffer(c);DCBTradeModel.changeWant(c,true);});await page.locator('nav [data-go="#trade"]').click();
 const chip=(side,value)=>page.locator('[data-side='+side+'][data-trade-rarity='+value+']');
 assert(!await page.locator('[data-trade=show]').isDisabled());await chip('offers','parallel').click();assert(!await page.locator('[data-trade=show]').isDisabled());await chip('wants','parallel').click();assert(await page.locator('[data-trade=show]').isDisabled());await chip('offers','all').click();assert(!await page.locator('[data-trade=show]').isDisabled());await chip('wants','all').click();
 await chip('offers','rare').click();await chip('wants','premium').click();assert.equal(await chip('offers','rare').getAttribute('aria-pressed'),'true');assert.equal(await chip('wants','premium').getAttribute('aria-pressed'),'true');assert.equal(await chip('wants','rare').getAttribute('aria-pressed'),'false');await page.screenshot({path:'preview-trade-home.png'});
 const criteria={offers:['rare'],wants:['premium']};await page.evaluate(()=>{window.tradeSessionOriginal=DCBTradeModel.session;DCBTradeModel.session=filters=>{window.lastTradePayload=window.tradeSessionOriginal(filters);return window.lastTradePayload;};});
 await page.locator('[data-trade=show]').click();await page.locator('.trade-page[data-trade-view=qr]').waitFor();assert.equal(await page.locator('.trade-qr svg').count(),1);assert.equal(await page.locator('.trade-page textarea').count(),0);assert.equal(await page.locator('[data-trade=scan]').count(),0);assert.equal(await page.locator('.trade-counts dd').first().textContent(),'1種類');assert.equal(await page.locator('.trade-counts dd').nth(1).textContent(),'1種類');const payload=await page.evaluate(()=>window.lastTradePayload);assert.deepEqual(payload.filters,criteria);assert.equal(await page.evaluate(p=>DCBData.cards.find(c=>c.id===p.offers[0].id).rarity,payload),'R');assert.equal(await page.evaluate(p=>DCBData.cards.find(c=>c.id===p.wants[0].id).rarity,payload),'PR');await page.screenshot({path:'preview-trade-qr.png'});
 await page.locator('.trade-page [data-trade=home]').click();await page.locator('.trade-qr-actions').waitFor();assert.equal(await chip('offers','rare').getAttribute('aria-pressed'),'true');
 await chip('offers','premium').click();assert.equal(await chip('offers','rare').getAttribute('aria-pressed'),'true');assert.equal(await chip('offers','premium').getAttribute('aria-pressed'),'true');await chip('offers','all').click();assert.equal(await chip('offers','premium').getAttribute('aria-pressed'),'false');await chip('wants','all').click();
 await page.locator('[data-trade=scan]').click();await page.locator('#trade-video').waitFor();await page.locator('[data-trade=demo]').click();await page.locator('.trade-match-heading').waitFor();assert.equal(await page.locator('.trade-match-heading').textContent(),'交換候補が4件見つかりました');assert.equal(await page.locator('.trade-section h2').first().textContent(),'あなたが渡せる');assert.equal(await page.locator('.trade-section h2').nth(1).textContent(),'相手からもらえる');assert(await page.locator('[data-trade=finish]').isDisabled());await page.screenshot({path:'preview-trade-matches.png'});await page.locator('#trade-confirmed').check();await page.locator('[data-trade=finish]').click();await page.locator('.trade-qr-actions').waitFor();assert.equal(await page.evaluate(id=>DCBStore.get(DCBData.cards.find(c=>c.id===id)).ownedCount,offerId),initial);
 await page.locator('[data-trade=scan]').click();await page.locator('#trade-video').waitFor();await page.evaluate(()=>{window.demoOriginal=DCBTradeModel.demo;DCBTradeModel.demo=()=>({...window.demoOriginal(),offers:[],wants:[]});});await page.locator('[data-trade=demo]').click();await page.locator('.trade-match-heading').waitFor();assert.equal(await page.locator('.trade-match-heading').textContent(),'今回は交換候補が見つかりませんでした');
 await page.locator('[data-trade=scan]').click();await page.locator('#trade-video').waitFor();await page.evaluate(()=>DCBTradeModel.demo=()=>({...window.demoOriginal(),createdAt:Date.now()-20000,expiresAt:Date.now()-10000}));await page.locator('[data-trade=demo]').click();assert((await page.locator('.trade-message').textContent()).includes('有効期限'));
 await page.locator('nav [data-go="#trade"]').click();await page.reload();await page.evaluate(()=>window.DCBReady);await page.locator('.opening').waitFor({state:'detached'});assert((await page.locator('.trade-heading').first().textContent()).includes('2 / 50'));assert((await page.locator('.trade-heading').nth(1).textContent()).includes('2 / 50'));
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});for(const view of ['', 'offers','add-offer','wants','add-want','qr','scan']){await page.evaluate(view=>location.hash='#trade'+(view?'/'+view:''),view);await page.waitForTimeout(60);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width+' '+view);}}
 assert.deepEqual(errors,[]);console.log('PASS: camera auto-start/stop, camera icon, independent multi-select rarity chips, direct QR/filtered payload, all reset, persisted inventory/wants, matching/no-match/expiry, 28 responsive screens');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
